{{- if and (not .Values.passwordSecretName) .Values.tidb.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cluster.name" . }}-tidb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tidb
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
  {{- if .Values.tidb.service.annotations }}
  annotations:
{{ toYaml .Values.tidb.service.annotations | indent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.tidb.auth.username }}-password: {{ template "tidb-cluster.tidb.password" . }}
{{- end }}
