apiVersion: v1
description: A Helm chart for TiDB Cluster
name: tidb-cluster
version: dev
home: https://github.com/pingcap/tidb-operator
sources:
  - https://github.com/pingcap/tidb-operator
keywords:
  - newsql
  - htap
  - database
  - mysql
  - raft
dependencies:
  - name: helm-utils
    repository: https://charts.nobidev.com
    version: 1.x.x
